### PR TITLE
Linux kernel: Add new category and myself to it

### PR DESCRIPTION
**Pull request by andy-shev**
Let's start new group.

### CODE REVIEW

**Comment by andy-shev** [comment]
If you have objections, please, feel free to close this and decide on your own how to proceed in better way. Thanks!

**Comment by lenadroid** [comment]
@andy-shev I was just thinking that "linux kernel" category might be too narrow for this list? Thinking of something broader, like "Operating Systems" related?... Also thinking of how to sort other mentors into categories to eliminate the list to be separated into just these two categories (linux and unsorted) for quite a while. Not closing yet, just thinking. Other people's opinions are welcome too.

**Comment by dotnwat** [comment]
maybe change the rather unused contact column as a keyword column

**Comment by andy-shev** [comment]
I'm about to remove the fork, sorry for noise.

**Pull request closed without merging**
