### PR TITLE
@Stakx

### PR DESCRIPTION
**Pull request by ghost**
Someone who has a lot of knowledge and is always willing to explain things. Please add!

### CODE REVIEW

**Comment by stakx** [comment]
Fine with me. Thanks for the kind words! :smile:

**Comment by lenadroid** [comment]
Thanks! Hey @stakx, it would be super cool if you added a contact in the `contact` column, so that people can reach you easily. what do you say?

**Comment by stakx** [comment]
@lenadroid: Sure. I didn't initiate this PR, so perhaps @fir3pho3nixx can add `<user name>@eml.cc` as my contact info. ;) Otherwise, let this PR go through and I'll separately add my contact info later on.

**Comment by ghost** [comment]
Reopened here: https://github.com/lenadroid/awesome-oss-mentors/pull/36

**Pull request closed without merging**
